import { MailTemplate } from "@/types/mail";

export const PRESET_HERO_IMAGES = [
    {
        id: "hero-render",
        name: "3D Dark Form (Screenshot)",
        url: "https://res.cloudinary.com/dabmjz0xr/image/upload/v1773854589/CadanceMetaImage_uwqmp8.png",
        description: "Minimalist black sculptural curvature with dramatic studio lighting",
    },
    {
        id: "portfolio-render",
        name: "Cadance Infinity",
        url: "https://res.cloudinary.com/dabmjz0xr/image/upload/v1790768193/CadanceInfinity_wbh2fo.png",
        description: "Cadance Infinity",
    },
    {
        id: "flow-render",
        name: "Cadance Flow Interface",
        url: "https://res.cloudinary.com/dabmjz0xr/image/upload/v1790770573/flow.cadancestudio.com_u5b1m7.png",
        description: "Cadance Flow Interface",
    },
];

export const COLOR_PRESETS = [
    { name: "Cadance Blue", hex: "#2972f5" },
    { name: "Emerald Teal", hex: "#10b981" },
    { name: "Cadance Violet", hex: "#8b5cf6" },
    { name: "Sunset Crimson", hex: "#f43f5e" },
    { name: "Warm Amber", hex: "#f59e0b" },
    { name: "Monochrome Silver", hex: "#a1a1aa" },
];

export const MAIL_TEMPLATES: MailTemplate[] = [
    {
        id: "standard-studio-mail",
        name: "Standard Studio Mail",
        category: "standard",
        description: "Genel duyurular, durum güncellemeleri ve resmi stüdyo yazışmaları için standart şablon",
        badge: "STANDART",
        defaultDesign: {
            accentColor: "#2972f5",
            themeMode: "dark",
            showHeroImage: false,
            heroImageUrl: "/images/cadance_hero_render.jpg",
            heroImageAlt: "Cadance Studio",
            studioName: "CADANCE STUDIO",
            buttonStyle: "rounded",
            fontFamily: "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            showCardBorder: true,
        },
        defaultContent: {
            clientEmail: "tunayekin.tuncer@gmail.com",
            clientName: "Sn. Değerli İş Ortağımız",
            subject: "Cadance Studio | Bilgilendirme ve Güncel Süreç Notları",
            preheader: "Cadance Studio ile yürüttüğümüz çalışmalar kapsamındaki resmi bilgilendirme notumuz.",
            badgeText: "İYİ ÇALIŞMALAR",
            badgeColor: "#2972f5",
            heading: "Merhaba,",
            highlightText: "Sn. Değerli İş Ortağımız,",
            leadParagraph: "Cadance Studio ile olan iş birliğimiz kapsamında güncel proje süreçleri, takvim planlaması ve iletişim kanalları hakkındaki notlarımızı bilgilerinize sunarız.",
            subheading: "Önemli Notlar & Süreç Adımları :",
            bulletPoints: [
                {
                    id: "std-1",
                    text: "Tüm tasarım teslimatları ve revizyon bildirimleri haftalık periyotlarla güncellenmektedir.",
                },
                {
                    id: "std-2",
                    text: "Süreç boyunca dosyalarınıza Cadance Flow üzerinden 7/24 kesintisiz erişim sağlayabilirsiniz.",
                },
                {
                    id: "std-3",
                    text: "Acil talepleriniz ve sorularınız için bu e-postayı doğrudan yanıtlayabilirsiniz.",
                },
            ],
            infoNotice: "Tüm yazışmalar stüdyomuzun gizlilik ilkeleri ve profesyonel standartları çerçevesinde korunmaktadır.",
            primaryButtonText: "Stüdyo Sayfamızı Ziyaret Edin",
            primaryButtonUrl: "https://www.cadancestudio.com",
            showSecondaryButton: false,
            secondaryButtonText: "Cadance Flow",
            secondaryButtonUrl: "https://flow.cadancestudio.com",
            footerNote: "Bu e-posta Cadance Studio kurumsal iletişim kanalı üzerinden iletilmiştir.",
            copyrightText: "© 2026 Cadance Studio. All rights reserved.",
        },
    },

    {
        id: "cadance-flow-invite",
        name: "Cadance Flow Invite",
        category: "cadance-flow",
        description: "Yeni başlayan proje için özel Cadance Flow takip portalı daveti",
        badge: "FLOW INVITE",
        defaultDesign: {
            accentColor: "#2972f5",
            themeMode: "dark",
            showHeroImage: true,
            heroImageUrl: "https://res.cloudinary.com/dabmjz0xr/image/upload/v1790770573/flow.cadancestudio.com_u5b1m7.png",
            heroImageAlt: "Cadance Studio 3D Form",
            studioName: "CADANCE STUDIO",
            buttonStyle: "rounded",
            fontFamily: "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            showCardBorder: true,
        },
        defaultContent: {
            clientEmail: "tunayekin.tuncer@gmail.com",
            clientName: "Sn. Tunay Ekin Tuncer",
            subject: "Cadance Flow | Yeni Proje Başlangıcı & Panel Erişim Bilgileri",
            preheader: "Projenizin tüm tasarım süreçlerini anlık olarak takip edebileceğiniz size özel Cadance Flow paneliniz hazırlandı.",
            badgeText: "YENİ PROJE BAŞLANGICI",
            badgeColor: "#d97706",
            heading: "Harika bir şeye başlıyoruz,",
            highlightText: "Sn. Tunay Ekin Tuncer",
            leadParagraph: "Stüdyomuzu tercih ettiğiniz için teşekkür ederiz. Projenizin tüm tasarım süreçlerini, revizyonlarını ve takvimini anlık olarak takip edebileceğiniz size özel Cadance Flow paneliniz hazırlandı.",
            subheading: "Nasıl giriş yapılır :",
            bulletPoints: [
                {
                    id: "step-1",
                    text: '"Proje sayfasına git" butonu ile projenin sayfasını üye olmadan görebilirsiniz.',
                },
                {
                    id: "step-2",
                    text: '"Cadance Flow\'a git" butonu ile Flow uygulamasının anasayfasına gidip bilgi edinebilir ve sonrasında üye olabilirsiniz.',
                },
                {
                    id: "step-3",
                    text: "Proje sayfasındaki tüm özellikleri kullanmak için lütfen üye olun. Üye olduktan sonra proje hesabınıza tanımlanacaktır.",
                },
            ],
            infoNotice: "Üye olmak için Google / Apple hesabınızı kullanabilir ya da mail ile hesap oluşturabilirsiniz.\nÜyelik bilgilerinizin tamamı korunmaktadır ve mail adresiniz, adınız ve profil fotoğrafınız dışındaki bilgiler bizimle paylaşılmamaktadır.",
            primaryButtonText: "Proje sayfasına git",
            primaryButtonUrl: "https://flow.cadancestudio.com",
            showSecondaryButton: true,
            secondaryButtonText: "Cadance Flow'a git",
            secondaryButtonUrl: "https://flow.cadancestudio.com",
            footerNote: "Bu e-posta yeni başlayan projenizin erişim bilgileri için gönderilmiştir.",
            copyrightText: "© 2026 Cadance Studio. All rights reserved.",
        },
    },

    {
        id: "portfolio-greeting",
        name: "Welcome & Portfolio Showcase",
        category: "portfolio",
        description: "Yeni müşterileri karşılama, mimari vizyon ve www.cadancestudio.com portfolyo tanıtımı",
        badge: "HOŞ GELDİNİZ",
        defaultDesign: {
            accentColor: "#8b5cf6",
            themeMode: "dark",
            showHeroImage: true,
            heroImageUrl: "/images/cadance_portfolio_hero.jpg",
            heroImageAlt: "Cadance Studio Architecture",
            studioName: "CADANCE STUDIO",
            buttonStyle: "pill",
            fontFamily: "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            showCardBorder: true,
        },
        defaultContent: {
            clientEmail: "tunayekin.tuncer@gmail.com",
            clientName: "Sn. Yeni Müşterimiz",
            subject: "Cadance Studio Dünyasına Hoş Geldiniz | Mimari & Tasarım Vizyonumuz",
            preheader: "Cadance Studio'nun seçkin mimarlık ve 3D tasarım projelerini keşfedin.",
            badgeText: "HOŞ GELDİNİZ",
            badgeColor: "#8b5cf6",
            heading: "Tasarım Vizyonumuza Hoş Geldiniz,",
            highlightText: "Sn. Müşterimiz,",
            leadParagraph: "Mimarlık, 3D görselleştirme, iç mekan renovasyonu ve dijital tasarım vizyonumuzla projelerinize değer katmaktan mutluluk duyuyoruz. Gerçekleştirdiğimiz seçkin projelerimizi ve güncel tasarım çalışmalarımızı web sitemizden inceleyebilirsiniz.",
            subheading: "Uzmanlık Alanlarımız & Hizmetlerimiz :",
            bulletPoints: [
                {
                    id: "pf-1",
                    text: "Özgün Mimari Çizim & Fotogerçekçi 3D Modelleme (Render) hizmetleri.",
                },
                {
                    id: "pf-2",
                    text: "İç Mekan & Dış Cephe Renovasyon Projeleri.",
                },
                {
                    id: "pf-3",
                    text: "Cadance Flow dijital proje yönetim paneli ile şeffaf ve anlık takip kolaylığı.",
                },
            ],
            infoNotice: "Yeni projeniz için keşif görüşmesi yapmak ve fikir alışverişinde bulunmak üzere stüdyomuzla dilediğiniz an iletişime geçebilirsiniz.",
            primaryButtonText: "Portfolyoyu İncele (cadancestudio.com)",
            primaryButtonUrl: "https://www.cadancestudio.com",
            showSecondaryButton: true,
            secondaryButtonText: "Keşif Toplantısı Planla",
            secondaryButtonUrl: "https://www.cadancestudio.com/#contact",
            footerNote: "Bu e-posta Cadance Studio yeni müşteri karşılama bilgilendirmesidir.",
            copyrightText: "© 2026 Cadance Studio. All rights reserved.",
        },
    },

    {
        id: "bid-contract",
        name: "Price Bid & Final Contract",
        category: "bid-contract",
        description: "Fiyat teklifleri, sözleşme şartnamesi, iş kalemleri ve onay süreci için özel şablon",
        badge: "TEKLİF & SÖZLEŞME",
        defaultDesign: {
            accentColor: "#10b981",
            themeMode: "dark",
            showHeroImage: true,
            heroImageUrl: "/images/cadance_flow_hero.jpg",
            heroImageAlt: "Cadance Contract",
            studioName: "CADANCE STUDIO",
            buttonStyle: "rounded",
            fontFamily: "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            showCardBorder: true,
        },
        defaultContent: {
            clientEmail: "tunayekin.tuncer@gmail.com",
            clientName: "Sn. Proje Yöneticisi",
            subject: "Cadance Studio | Proje Fiyat Teklifi ve Sözleşme Şartnamesi",
            preheader: "Görüşmelerimiz doğrultusunda hazırlanan proje fiyat teklifi ve sözleşme detayları ekte yer almaktadır.",
            badgeText: "FİYAT TEKLİFİ & SÖZLEŞME",
            badgeColor: "#10b981",
            heading: "Proje Teklifi & Sözleşme Detayları,",
            highlightText: "Sn. Yetkili,",
            leadParagraph: "Görüşmelerimiz ve teknik gereksinimler doğrultusunda projeniz için hazırladığımız kapsamlı iş planı, maliyet tablosu ve sözleşme şartnamesi bilgilerinize sunulmuştur.",
            subheading: "Teklif & Kapsam Özeti :",
            bulletPoints: [
                {
                    id: "bid-1",
                    text: "Kapsam: Konsept Mimari Proje, 3D Render Modelleme & Uygulama Detayları.",
                },
                {
                    id: "bid-2",
                    text: "Ödeme Planı: %40 Proje Başlangıcı Avansı, %30 Ara Revizyon Onayı, %30 Nihai Teslimat.",
                },
                {
                    id: "bid-3",
                    text: "Süreç Takibi: Tüm revizyonlar Cadance Flow portalı üzerinden yürütülecektir.",
                },
            ],
            infoNotice: "İşbu teklif ve şartname gönderim tarihinden itibaren 15 gün süreyle geçerlidir. Teklifin onaylanması durumunda sözleşme karşılıklı olarak yürürlüğe girecektir.",
            primaryButtonText: "Sözleşmeyi İncele & Onayla",
            primaryButtonUrl: "https://www.cadancestudio.com/proposals",
            showSecondaryButton: true,
            secondaryButtonText: "Cadance Flow Paneline Git",
            secondaryButtonUrl: "https://flow.cadancestudio.com",
            footerNote: "Bu e-posta proje fiyat teklifi ve sözleşme müzakereleri kapsamında özel olarak iletilmiştir.",
            copyrightText: "© 2026 Cadance Studio. All rights reserved.",
            bidDetails: {
                projectName: "Modern Villa & Çevre Düzenleme",
                scopeText: "Avan Proje + 3D Render + Ruhsat Çizimleri",
                priceAmount: "₺75.000 + KDV",
                validityPeriod: "15 Gün Geçerli",
            },
        },
    },

    {
        id: "milestone-revision",
        name: "Milestone & Revision Delivery",
        category: "milestone",
        description: "Teslim edilen renderlar, paftalar ve yeni tasarım revizyonlarını müşteriye duyurma şablonu",
        badge: "TESLİMAT",
        defaultDesign: {
            accentColor: "#f59e0b",
            themeMode: "dark",
            showHeroImage: true,
            heroImageUrl: "/images/cadance_hero_render.jpg",
            heroImageAlt: "Milestone Delivery",
            studioName: "CADANCE STUDIO",
            buttonStyle: "rounded",
            fontFamily: "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            showCardBorder: true,
        },
        defaultContent: {
            clientEmail: "tunayekin.tuncer@gmail.com",
            clientName: "Sn. Proje Sahibi",
            subject: "Cadance Studio | Yeni Render Görselleri ve Revizyonlar Panelinize Eklendi",
            preheader: "Projenizde tamamlanan yeni aşamaya ait renderlar ve teknik çizimler Cadance Flow panelinizde yayında.",
            badgeText: "YENİ PROJE AŞAMASI",
            badgeColor: "#f59e0b",
            heading: "Yeni Tasarım Aşaması Tamamlandı,",
            highlightText: "Sn. Proje Sahibi,",
            leadParagraph: "Projenizin tasarım sürecinde kararlaştırılan yeni aşama başarıyla tamamlanmış olup, yüksek çözünürlüklü renderlar ve güncel teknik çizimler Cadance Flow panelinize yüklenmiştir.",
            subheading: "Teslim Edilen Öğeler & Yenilikler :",
            bulletPoints: [
                {
                    id: "ms-1",
                    text: "4K Dış Cephe & İç Mekan Gün Işığı / Gece Aydınlatma renderları.",
                },
                {
                    id: "ms-2",
                    text: "Güncellenmiş mobilya yerleşim ve malzeme detay paftaları.",
                },
                {
                    id: "ms-3",
                    text: "Revizyon ve geri bildirim notlarınızı panel üzerinden doğrudan iletebilirsiniz.",
                },
            ],
            infoNotice: "Yorum yapmak ya da aşamaya onay vermek için üye girişi yapmalısınız.Tasarım detaylarını inceleyip geri bildirimlerinizi ilettikten sonra sonraki teknik aşamaya geçilecektir.",
            primaryButtonText: "Çizimleri & Renderları İncele",
            primaryButtonUrl: "https://flow.cadancestudio.com",
            showSecondaryButton: true,
            secondaryButtonText: "Revizyon Notu İlet",
            secondaryButtonUrl: "https://flow.cadancestudio.com/feedback",
            footerNote: "Bu e-posta Cadance Studio proje teslimat takip sistemi tarafından iletilmiştir.",
            copyrightText: "© 2026 Cadance Studio. All rights reserved.",
        },
    },
];
